/*
	Copyright (c) 1987, 1988, 1989, 1990 by Tektronix, Inc.

    It may freely be redistributed and modified so long as the copyright
    notices and credit attributions remain intact.
 */
#include "mon.h"

main()
{
    int i;

    struct all_vars v;
    printf("/*\n");
    printf(" * This file is automatically generated when the ROMs are\n");
    printf(" * built.  This has the structure offsets of the all_vars\n");
    printf(" * structure, which is used by code in mon.c and monstart.s\n");
    printf(" */\n");
    printf("\n");
    for (i = 0 ; i < 32 ; i++) {
      printf("\tDM_REG_R%d = %d\n", i, soff(dm_genregs[i]));
    }
    printf("\tDM_REG_IP = %d\n", soff(dm_ip));
    printf("\tDM_REG_PID = %d\n", soff(dm_pid));
    printf("\tDM_REG_PSR = %d\n", soff(dm_psr));
    printf("\tDM_REG_TPSR = %d\n", soff(dm_tpsr));
    printf("\tDM_REG_SSBR = %d\n", soff(dm_ssbr));
    printf("\tDM_REG_SXIP = %d\n", soff(dm_sxip));
    printf("\tDM_REG_SNIP = %d\n", soff(dm_snip));
    printf("\tDM_REG_SFIP = %d\n", soff(dm_sfip));
    printf("\tDM_REG_VBR = %d\n", soff(dm_vbr));

    printf("\tDM_REG_DMT0 = %d\n", soff(dm_dmt0));
    printf("\tDM_REG_DMA0 = %d\n", soff(dm_dma0));
    printf("\tDM_REG_DMD0 = %d\n", soff(dm_dmd0));

    printf("\tDM_REG_DMT1 = %d\n", soff(dm_dmt1));
    printf("\tDM_REG_DMA1 = %d\n", soff(dm_dma1));
    printf("\tDM_REG_DMD1 = %d\n", soff(dm_dmd1));

    printf("\tDM_REG_DMT2 = %d\n", soff(dm_dmt2));
    printf("\tDM_REG_DMA2 = %d\n", soff(dm_dma2));
    printf("\tDM_REG_DMD2 = %d\n", soff(dm_dmd2));

    printf("\tDM_REG_SR0 = %d\n", soff(dm_sr0));
    printf("\tDM_REG_SR1 = %d\n", soff(dm_sr1));
    printf("\tDM_REG_SR2 = %d\n", soff(dm_sr2));
    printf("\tDM_REG_SR3 = %d\n", soff(dm_sr3));

    printf("\tDM_REG_FPECR = %d\n", soff(dm_ip));
    printf("\tDM_REG_FPHS1 = %d\n", soff(dm_fphs1));
    printf("\tDM_REG_FPLS1 = %d\n", soff(dm_fpls1));
    printf("\tDM_REG_FPHS2 = %d\n", soff(dm_fphs2));
    printf("\tDM_REG_FPLS2 = %d\n", soff(dm_fpls2));

    printf("\tDM_REG_FPPT = %d\n", soff(dm_fppt));
    printf("\tDM_REG_FPRH = %d\n", soff(dm_fprh));
    printf("\tDM_REG_FPRL = %d\n", soff(dm_fprl));
    printf("\tDM_REG_FPIT = %d\n", soff(dm_fpit));
    printf("\tDM_REG_FPSR = %d\n", soff(dm_fpsr));
    printf("\tDM_REG_FPCR = %d\n", soff(dm_fpcr));
    printf("\tDM_REG_CE_INTR_MSK = %d\n", soff(dm_ce_intr_msk));
    printf("\tDM_EXCEPTION_CODE = %d\n", soff(dm_exception_code));
    printf("\tDM_IN_MON = %d\n", soff(dm_in_mon));
    printf("\tDM_DACC_ADDRESS = %d\n", soff(dm_dacc_address));
    printf("\tDM_CALL_ON_MON_ENTRY = %d\n", soff(dm_call_on_mon_entry));
    printf("\tDM_CALL_ON_MON_EXIT = %d\n", soff(dm_call_on_mon_exit));
    printf("\tDM_RESTART_COUNT = %d\n", soff(dm_restart_count));
    printf("#define\tDM_SIZEOF_ALL_VARS\t(%d)\n", roundup(sizeof v));
    printf("#define\tDM_STACK\t(%d)\n", 
				roundup(soff(dm_stackarea[MONSTACKSIZE])));

    exit(0);
}

/*
 * Return the least multiple of 8 greater than or equal to the passed
 * argument.
 */
roundup(i)
    unsigned i;
{
    return (i + 7) & ~7;
}
